# Generated by Django 3.2 on 2021-09-13 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='body_uz',
        ),
    ]
