# Generated by Django 3.2 on 2021-09-13 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_template_body_uz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotUserInfo',
        ),
    ]
