# Generated by Django 3.2 on 2021-09-13 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210913_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='body_en',
            new_name='body_ua',
        ),
    ]
