# Generated by Django 3.2 on 2021-09-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_body_en_template_body_ua'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='lang',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
