# Generated by Django 3.2 on 2021-09-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_botuser_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='bot_state',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
