# Generated by Django 3.2 on 2021-09-13 02:07

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_botuser_bot_state'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('categories', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.AddField(
            model_name='category',
            name='name_ua',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.category'),
        ),
    ]
