# Generated by Django 3.2 on 2021-09-13 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210913_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
    ]
